import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";
import Layout from "@/app/components/Layout";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* eslint-disable-next-line react/no-children-prop */}
      <header><Layout children={undefined}/></header>
      <main>{children}</main>
      <Footer/>
      </body>
    </html>
  )
}
